In [13]:
from sklearn.preprocessing import LabelEncoder
def fillna(df):
    df['Age'].fillna(titanic_df['Age'].mean(), inplace=True)
    df['Cabin'].fillna('N', inplace=True)
    df['Embarked'].fillna('N', inplace=True)
    df['Fare'].fillna(0, inplace=True)
    return df

#머신러닝 알고리즘에 불필요한 속성 제거
def drop_features(df):
    df.drop(['PassengerId', 'Name', 'Ticket'], axis=1, inplace=True)
    return df

#레이블 인코딩 수행
def format_features(df):
    df['Cabin'] = df['Cabin'].str[:1]
    features = ['Cabin', 'Sex', 'Embarked']
    for feature in features:
        le = LabelEncoder()
        le = le.fit(df[feature])
        df[feature] = le.transform(df[feature])
    return df

def transform_features(df):
    df = fillna(df)
    df = drop_features(df)
    df = format_features(df)
    return df

In [14]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

titanic_df = pd.read_csv('./titanic_train.csv')
y_titanic_df = titanic_df['Survived']
X_titanic_df = titanic_df.drop('Survived', axis=1)
X_titanic_df = transform_features(X_titanic_df)

X_train, X_test, y_train, y_test = train_test_split(X_titanic_df, y_titanic_df, test_size=0.2, random_state=11)

lr_clf = LogisticRegression()

lr_clf.fit(X_train, y_train)
pred = lr_clf.predict(X_test)
get_clf_eval(y_test, pred)

오차행렬
[[104  14]
 [ 13  48]]
정확도: 0.8492, 정밀도: 0.7742, 재현율: 0.7869


In [18]:
import numpy as np

pred_proba = lr_clf.predict_proba(X_test)
pred = lr_clf.predict(X_test)
print(f'pred_proba() 결과 shape: {pred_proba.shape}')
print(f'pred_proba array에서 앞 3개만 샘플로 추출 \n:{pred_proba[:3]}')

pred_proba_result = np.concatenate([pred_proba, pred.reshape(-1,1)], axis = 1)
print('두 개의 class 중에서 더 큰 확률을 클래스 값으로 예측 \n', pred_proba_result[:3])

pred_proba() 결과 shape: (179, 2)
pred_proba array에서 앞 3개만 샘플로 추출 
:[[0.46210752 0.53789248]
 [0.87868089 0.12131911]
 [0.87716101 0.12283899]]
두 개의 class 중에서 더 큰 확률을 클래스 값으로 예측 
 [[0.46210752 0.53789248 1.        ]
 [0.87868089 0.12131911 0.        ]
 [0.87716101 0.12283899 0.        ]]


In [20]:
print(pred_proba[:,1].reshape(-1,1))

[[0.53789248]
 [0.12131911]
 [0.12283899]
 [0.1174082 ]
 [0.14461558]
 [0.11778459]
 [0.11157798]
 [0.79117393]
 [0.21704793]
 [0.63065775]
 [0.10022231]
 [0.12493722]
 [0.12284495]
 [0.11162375]
 [0.56331971]
 [0.1410109 ]
 [0.09624082]
 [0.26657306]
 [0.27512926]
 [0.8283008 ]
 [0.24640074]
 [0.38080712]
 [0.14537192]
 [0.1852803 ]
 [0.11199334]
 [0.23449928]
 [0.14035782]
 [0.07415405]
 [0.28039696]
 [0.30437797]
 [0.94717762]
 [0.81724192]
 [0.12684517]
 [0.82611185]
 [0.39932365]
 [0.23449928]
 [0.07237998]
 [0.61085551]
 [0.05289489]
 [0.10391804]
 [0.3508219 ]
 [0.08336214]
 [0.82168265]
 [0.70754453]
 [0.63041004]
 [0.63042628]
 [0.91882337]
 [0.35889493]
 [0.94881756]
 [0.11202777]
 [0.59265842]
 [0.11162375]
 [0.13278582]
 [0.72514861]
 [0.30931558]
 [0.19704277]
 [0.22631982]
 [0.12284003]
 [0.15419186]
 [0.43234499]
 [0.28010599]
 [0.10071566]
 [0.54535719]
 [0.51408311]
 [0.44429239]
 [0.09460203]
 [0.66670251]
 [0.59404061]
 [0.95179236]
 [0.14819224]
 [0.12882713]
 [0.16

In [22]:
from sklearn.preprocessing import Binarizer

pred_proba_1 = pred_proba[:,1].reshape(-1,1)
binarizer = Binarizer(threshold=0.5).fit(pred_proba_1)
cus_pre = binarizer.transform(pred_proba_1)
print(cus_pre)

[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.

In [23]:
get_clf_eval(y_test, cus_pre)

오차행렬
[[104  14]
 [ 13  48]]
정확도: 0.8492, 정밀도: 0.7742, 재현율: 0.7869
